Productdetail
desafree/ecommerce pull request #12
Opened 2022-12-29 09:31 UTC by desafree

Create the product detail ui. Content on page change based on the url

2022-12-29 09:33 UTC, desafree commented
Ci sono un pò più di 20 file modificati perchè non volevo spezzare in due la PR

2022-12-29 10:16 UTC, rams23 requested changes

2022-12-29 10:16 UTC, rams23 commented on src/_shared/components/Grid/Grid.tsx
>      <GridMUI
come mai abbiamo dovuto dividere così?

2022-12-29 10:16 UTC, rams23 commented on src/_shared/components/HalfSectionList/HalfSectionList.tsx
>    title1: string;
Megli usare nomi più espliciti e non title1 e title2

2022-12-29 10:16 UTC, rams23 commented on src/_shared/components/HalfSectionList/HalfSectionList.tsx
> +                disablePadding={true}
rimuovere i true

2022-12-29 10:16 UTC, rams23 commented on src/products/components/ButtonProduct/ButtonProduct.styled.tsx
> +      text-align: center;
si può usare Typography

2022-12-29 10:16 UTC, rams23 commented on src/products/components/ButtonProduct/ButtonProduct.tsx
> +      </div>
Meglio usare i componenti che abbiamo

2022-12-29 10:16 UTC, rams23 commented on src/products/components/ProductDetail/ProductDetail.tsx
> +      <button onClick={handleClick}>Go back</button>
component e traslations

2022-12-29 10:16 UTC, rams23 commented on src/products/components/ProductImages/ProductImages.styled.tsx
> +  imageList: string[];
se ci devono sempre essere treimmagini melgio usare [string, string, string], altrimenti potrei passare un array vuoto

2022-12-29 14:30 UTC, desafree commented on src/_shared/components/Grid/Grid.tsx
>      <GridMUI
alcuni props (come columnSpacing o direction) sono specifici per <Grid container> mentre altri (come sx o md) solo per <Grid item>

2022-12-30 09:26 UTC, rams23 approved these changes

2022-12-30 09:44 UTC, merged