order confirmation popup
desafree/ecommerce pull request #18
Opened 2023-01-09 16:03 UTC by desafree

create the order confirmation popup. Because the payment functionality is not implemented, after the checkout the user will be redirected to the homepage and the cart will be cleared

2023-01-09 17:40 UTC, rams23 requested changes

2023-01-09 17:40 UTC, rams23 commented on src/checkout/components/ItemsRecap/ItemsRecap.tsx
> +  const items = useSelectProductsFromCart();
useSelect discloses implementation details that are not necessary, i would rather use something like "useCartProducts" or "useProducts in cart", or just useCart, returning items as an object

2023-01-09 17:40 UTC, rams23 commented on src/checkout/components/OrderDetailRecap/OrderDetailRecap.tsx
> +      {!on ? (
renaming on as viewMore will make this component a lot clearer

2023-01-09 17:40 UTC, rams23 commented on src/checkout/components/OrderRecap/OrderRecap.tsx
> +};
can we use the popup component in this situation?

2023-01-09 17:40 UTC, rams23 commented on src/checkout/views/Checkout/Checkout.tsx
> +  const { toggle, on } = useToggle();
also this "on" could be something like "showRecap"

2023-01-10 09:07 UTC, desafree commented on src/checkout/components/OrderRecap/OrderRecap.tsx
> +};
do you mean in terms of content or for the popup functionality itself?

2023-01-10 14:39 UTC, desafree commented
Not so sure about using React.Children.map + React.cloneElement to pass ref to my popup container (passed as a child)

2023-01-11 11:31 UTC, rams23 approved these changes

2023-01-11 13:16 UTC, merged